#the code below was generated by chatGPT
#with the prompt:
#
# chatGPT, can you provide me some ruby code to use selenium to open a 
# chrome browser, search for the term "how to reduce the cost of 
# software testing", and verify a link exists to the book?
#
#
#
# This code is by (ish?) Matthew Heusser Matt@xndev.com

require 'selenium-webdriver'

# Initialize the Chrome driver
driver = Selenium::WebDriver.for :chrome

# Navigate to the URL
driver.get "https://www.google.com"

# Locate the search bar and enter the search term
search_bar = driver.find_element(name: "q")
search_bar.send_keys "how to reduce the cost of software testing"
search_bar.submit

# Check if a link to the book exists
begin
  driver.find_element(partial_link_text: "How to Reduce the Cost of Software Testing")
  puts "Link to the book found"
rescue Selenium::WebDriver::Error::NoSuchElementError
  puts "Link to the book not found"
end

# Close the browser
driver.quit
